/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.vertigo.gradle;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;

public class App implements RequestHandler<Object, String> {
    // public String getGreeting() {
    //     return "hw!";
    // }

    // public static void main(String[] args) {
    //     System.out.println(new App().getGreeting());
    // }

	@Override
	public String handleRequest(Object input, Context context) {
		context.getLogger().log("Input: " + input);
		String output = "Hello, " + input + "!";
  		return output;
	}
}
